---
services:

  connect:
    image: confluentinc/cp-kafka-connect-base:7.9.2.arm64
    hostname: connect
    container_name: connect
    user: root
#    depends_on:
#      - broker
#      - schema-registry
    ports:
      - "8083:8083"
    volumes:
      - /Users/radek/projects/radek/local_config/kafka/connect/snowflake.properties:/opt/snowflake.properties:rw
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

      # Enable Config Providers
      CONNECT_CONFIG_PROVIDERS: "file,env"
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: "org.apache.kafka.common.config.provider.FileConfigProvider"
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: "org.apache.kafka.common.config.provider.EnvVarConfigProvider"
    command:
      - bash
      - -c
      - |
        echo "Installing Connectors"
        #
        confluent-hub install --no-prompt snowflakeinc/snowflake-kafka-connector:latest
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run

networks:
  default:
    name: bigdatanetwork
    driver: bridge
    external: true
