apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jupyter
  namespace: jupyter
  labels:
    app: jupyter
    tier: jupyter
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: jupyter
  template:
    metadata:
      labels:
        tier: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888
