
rootUser: "minioadmin"
rootPassword: "minioadmin"

drivesPerNode: 1
replicas: 2
pools: 1

persistence:
  size: 100Gi

resources:
  requests:
    memory: 4Gi

users:
  - accessKey: console
    secretKey: console123
    policy: consoleAdmin

buckets:
  - name: dremio
    policy: none
    purge: false
    versioning: false
    objectlocking: false
  - name: test
    policy: none
    purge: false
    versioning: false
    objectlocking: false
