apiVersion: v1
kind: Namespace
metadata:
  name: k8s-jobs-prod

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: k8s-jobs-prod

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: k8s-jobs-prod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - scheduledsparkapplications
  - scheduledsparkapplications/status
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-spark-role-binding
  namespace: k8s-jobs-prod
subjects:
- kind: ServiceAccount
  name: spark
  namespace: k8s-jobs-prod
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
