
hub:
  config:
    GitHubOAuthenticator:
      client_id: # pass this value, see $GITHUB_CLIENT_ID in jupyterhub.md
      client_secret: # pass this value, see $GITHUB_CLIENT_SECRET in jupyterhub.md
      oauth_callback_url: http://localhost:8080/hub/oauth_callback
    JupyterHub:
      authenticator_class: github
  extraConfig:
    00-first-config: |
      def notebook_dir_hook(spawner):
          print("************************ notebook_dir_hook")
          print(list(spawner.environment))
          spawner.environment['NB_USER'] = spawner.user.name
          spawner.environment['GRANT_SUDO'] = "yes"
          spawner.environment['CHOWN_HOME'] = "yes"
          # spawner.environment['NB_UID'] = "500"
      c.Spawner.pre_spawn_hook = notebook_dir_hook
      c.KubeSpawner.allow_privilege_escalation=True
      # c.KubeSpawner.args = ['--allow-root']

singleuser:
  uid: 0
  storage:
    homeMountPath: "/home/{username}"
  extraEnv:
    RADZIO: radzio123
    EDITOR: "vim"
  image:
    name: jupyter/minimal-notebook
    tag: 2022-04-24
  profileList:
    - display_name: "Python Notebooks"
      description: "Minimal Jupyter Notebook Stack"
      default: true
    - display_name: "Scientific Python (SciPy) Notebooks"
      description: "Jupyter Notebook Scientific Python Stack"
      kubespawner_override:
        image: jupyter/scipy-notebook:2022-04-24
    - display_name: "Datascience Notebooks"
      description: "Jupyter Notebook Data Science Stack"
      kubespawner_override:
        image: jupyter/datascience-notebook:2022-04-24
    - display_name: "R Notebooks"
      description: "Jupyter Notebook R Stack"
      kubespawner_override:
        image: jupyter/r-notebook:2022-04-24
    - display_name: "Tensorflow Notebooks"
      description: "Jupyter Notebook Deep Learning Stack"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:2022-04-24
    - display_name: "PySpark Notebooks"
      description: "Jupyter Notebook Python, Spark Stack"
      kubespawner_override:
        image: jupyter/pyspark-notebook:2022-04-24
    - display_name: "Spark Scala Notebooks"
      description: "Jupyter Notebook Python, Scala, R, Spark Stack"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2022-04-24
