
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.default_url = "/lab"

singleuser:
  extraEnv:
    NB_USER: "radek"
    GRANT_SUDO: "yes"
    NB_UID: "146"
    # NOTEBOOK_ARGS: "--allow-root"
  allowPrivilegeEscalation: true
  uid: 0
  serviceAccountName: jovyan
  cmd: null
  defaultUrl: "/lab"
  image:
    name: bigdatapassion/jupyter
    tag: latest
  profileList:
    - display_name: "BigDataPassion Jupyter Notebook"
      description: "BigDataPassion Jupyter Notebook"
      default: true
    - display_name: "Python Notebooks"
      description: "Minimal Jupyter Notebook Stack"
      kubespawner_override:
        image: jupyter/minimal-notebook:2022-11-14
    - display_name: "Scientific Python (SciPy) Notebooks"
      description: "Jupyter Notebook Scientific Python Stack"
      kubespawner_override:
        image: jupyter/scipy-notebook:2022-11-14
    - display_name: "Datascience Notebooks"
      description: "Jupyter Notebook Data Science Stack"
      kubespawner_override:
        image: jupyter/datascience-notebook:2022-11-14
    - display_name: "R Notebooks"
      description: "Jupyter Notebook R Stack"
      kubespawner_override:
        image: jupyter/r-notebook:2022-11-14
    - display_name: "Tensorflow Notebooks"
      description: "Jupyter Notebook Deep Learning Stack"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:2022-11-14
    - display_name: "PySpark Notebooks"
      description: "Jupyter Notebook Python, Spark Stack"
      kubespawner_override:
        image: jupyter/pyspark-notebook:2022-11-14
    - display_name: "Spark Scala Notebooks"
      description: "Jupyter Notebook Python, Scala, R, Spark Stack"
      kubespawner_override:
        image: jupyter/all-spark-notebook:spark-3.1.1
    - display_name: "GetInData MLOps (dev-latest)"
      description: "https://github.com/getindata/jupyter-images"
      kubespawner_override:
        image: gcr.io/getindata-images-public/jupyterlab-mlops:dev-latest
    - display_name: "GetInData DataOps 1.2.0"
      description: "https://github.com/getindata/jupyter-images"
      kubespawner_override:
        image: gcr.io/getindata-images-public/jupyterlab-dataops:jupyterhub-1.2.0
    - display_name: "GetInData Streaming (1.0.1)"
      description: "https://github.com/getindata/jupyter-images"
      kubespawner_override:
        image: gcr.io/getindata-images-public/jupyterlab-streaming:1.0.1

prePuller:
  pullProfileListImages: false
  hook:
    enabled: false
  continuous:
    enabled: false

debug:
  enabled: true
