apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "osa-wiki-import-{{ ts_nodash.replace('T', '-') }}-{{ task_instance.try_number }}"
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1"
  imagePullPolicy: Always
  mainClass: pl.osaweb.crawler.wikipedia.WikipediaImport
  mainApplicationFile: "hdfs://hadoopbackup.osaweb.pl:8020/tmp/jars/osa-jobs.jar"
  arguments:
    - "-master"
    - "k8s://https://192.168.59.111:8443"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 2
    memory: "8g"
    labels:
      version: 3.1.1
    serviceAccount: airflow-worker
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 2
    instances: 1
    memory: "8g"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
