version: '3.5'

services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper
    networks:
      - kafkanetwork

  zookeeperdr:
    container_name: zookeeperdr
    hostname: zookeeperdr
    image: wurstmeister/zookeeper
    networks:
      - kafkanetwork

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: wurstmeister/kafka:2.12-2.5.0
    networks:
      - kafkanetwork
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./config:/opt/kafka/mirrormaker
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: wurstmeister/kafka:2.12-2.5.0
    networks:
      - kafkanetwork
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - kafka1

  kafkadr1:
    container_name: kafkadr1
    hostname: kafkadr1
    image: wurstmeister/kafka:2.12-2.5.0
    networks:
      - kafkanetwork
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeperdr:2181
    depends_on:
      - zookeeperdr

  kafkadr2:
    container_name: kafkadr2
    hostname: kafkadr2
    image: wurstmeister/kafka:2.12-2.5.0
    networks:
      - kafkanetwork
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeperdr:2181
    depends_on:
      - kafkadr1

  kafka-manager:
      container_name: kafka-manager
      hostname: kafka-manager
      image: solsson/kafka-manager
      ports:
        - "9000:9000"
      networks:
        - kafkanetwork
      depends_on:
        - kafka2
      environment:
          ZK_HOSTS: zookeeper:2181
          APPLICATION_SECRET: letmein
          KM_ARGS: -Djava.net.preferIPv4Stack=true

networks:
  kafkanetwork:
    driver: bridge