apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
  namespace: jupyter-ns
spec:
  containers:
  - name: jupyter-con
    image: jupyter/minimal-notebook:latest
    ports:
    - containerPort: 8888
