apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bigdatapassion
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100

availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']
