apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  admissionController.filtering.processNamespaces: "k8s-jobs"
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: tag
            value: namespace
            create: true
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: k8s-jobs-dev
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 3G, vcore: 2}
                  max:
                    {memory: 9G, vcore: 6}
              - name: k8s-jobs
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 12G, vcore: 8}
                  max:
                    {memory: 40G, vcore: 11}
