apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  admissionController.filtering.processNamespaces: "k8s-jobs"
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: tag
            value: namespace
            create: true
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: dev
                submitacl: '*'
              - name: k8s-jobs
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 4G, vcore: 2}
                  max:
                    {memory: 8G, vcore: 4}
