apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
#  admissionController.filtering.processNamespaces: "k8s-jobs"
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: tag
            value: namespace
            create: true
        queues:
          - name: root
            submitacl: '*'
            maxapplications: 8
            properties:
              priority.policy: default
              priority.offset: 0
              application.sort.priority: enabled
              application.sort.policy: fifo
              preemption.policy: fence
              preemption.delay: 10s
            queues:
              - name: k8s-jobs-dev
                submitacl: '*'
                maxapplications: 4
                resources:
                  guaranteed:
                    {memory: 20G, vcore: 2}
                  max:
                    {memory: 120G, vcore: 12000m}
                properties:
                  priority.policy: default
                  priority.offset: 0
                  application.sort.priority: enabled
                  application.sort.policy: fifo
                  preemption.policy: fence
                  preemption.delay: 10s
              - name: k8s-jobs-prod
                submitacl: '*'
                maxapplications: 4
                resources:
                  guaranteed:
                    {memory: 100G, vcore: 10}
                  max:
                    {memory: 120G, vcore: 12000m} 
                properties:
                  priority.policy: default
                  priority.offset: 100000
                  application.sort.priority: enabled
                  application.sort.policy: fifo
                  preemption.policy: fence
                  preemption.delay: 10s
