apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
#  admissionController.filtering.processNamespaces: "k8s-jobs"
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: tag
            value: namespace
            create: true
        queues:
          - name: root
            submitacl: '*'
            maxapplications: 6
            properties:
              priority.policy: default
              priority.offset: 0
              application.sort.priority: enabled
              application.sort.policy: fifo
            queues:
              - name: k8s-jobs-dev
                submitacl: '*'
                maxapplications: 3
                resources:
                  guaranteed:
                    {memory: 10G, vcore: 2}
                  max:
                    {memory: 126G, vcore: 12000m}
                properties:
                  priority.policy: default
                  priority.offset: 0
                  application.sort.priority: enabled
                  application.sort.policy: fifo
              - name: k8s-jobs-prod
                submitacl: '*'
                maxapplications: 3
                resources:
                  guaranteed:
                    {memory: 10G, vcore: 2}
                  max:
                    {memory: 126G, vcore: 12000m} 
                properties:
                  priority.policy: default
                  priority.offset: 100
                  application.sort.priority: enabled
                  application.sort.policy: fifo
