apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
#  admissionController.filtering.processNamespaces: "k8s-jobs"
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: tag
            value: namespace
            create: true
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: k8s-jobs-dev
                submitacl: '*'
                maxapplications: 1
                resources:
                  guaranteed:
                    {memory: 63G, vcore: 7720m}
                  max:
                    {memory: 63G, vcore: 7720m}
                properties:
                  priority.policy: default
                  priority.offset: 0
                  application.sort.priority: enabled
                  application.sort.policy: fifo
              - name: k8s-jobs-prod
                submitacl: '*'
                maxapplications: 1
                resources:
                  guaranteed:
                    {memory: 63G, vcore: 7720m}
                  max:
                    {memory: 63G, vcore: 7720m} 
                properties:
                  priority.policy: default
                  priority.offset: 100
                  application.sort.priority: enabled
                  application.sort.policy: fifo
