
webserver:
  service:
    type: LoadBalancer

config:
  core:
    load_examples: 'True'

dags:
  gitSync:
    enabled: true
    repo: https://github.com/apache/airflow.git
    branch: main
    subPath: "airflow/providers/cncf/kubernetes/example_dags"
