
image:
  repository: apache/superset
  tag: 2.0.0
  pullPolicy: Always

initImage:
  repository: busybox
  tag: 1.34.1
  pullPolicy: Always

service:
  type: LoadBalancer

init:
  loadExamples: true

bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  pip install \
    pyhive \
    sqlalchemy-trino \
    pybigquery \
    snowflake-sqlalchemy \
    "PyAthenaJDBC>1.0.9 \
    "PyAthena>1.2.0 \
    psycopg2-binary==2.9.1 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi