
image:
  repository: apache/superset
  tag: latest
  pullPolicy: Always

initImage:
  repository: busybox
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer

init:
  loadExamples: true

bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  pip install \
    pybigquery
    snowflake-sqlalchemy
    pyhive
    psycopg2-binary==2.9.1 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi