apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  namespace: coder

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder
  namespace: coder
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: coder
roleRef:
  kind: Role
  name: coder
  apiGroup: rbac.authorization.k8s.io
